language: ruby

rvm:
    - 2.3.1

services:
    - mysql

gemfile: app/Gemfile

before_script:
    - "mysql -u root -e \"create database slp_pauselab_test;\""
    - "mysql -u root -e \"grant all on slp_pauselab_test.* to 'pauselab';\""
    - cd app

script: 
    - ls 
    - bundle exec bin/rails db:migrate RAILS_ENV=test
    - bundle exec rake

notifications:
    email:
        on_success: never
        on_failure: always
    notifications:
        slack: slp-pauselab:TaS7lyjK15WmuNh3p44WYvyS

sudo: false
