# language: ruby
#
# rvm:
#     - 2.3.1
#
# services:
#     - mysql
#
# gemfile: app/Gemfile
#
# before_script:
#     - "mysql -u root -e \"create database slp_pauselab_test;\""
#     - "mysql -u root -e \"grant all on slp_pauselab_test.* to 'pauselab';\""
#     - cd app
#
# script:
#     - ls
#     - bin/rails db:schema:load RAILS_ENV=test
#     - bundle exec rake
#
# notifications:
#     email:
#         on_success: never
#         on_failure: always
#     notifications:
#         slack: slp-pauselab:TaS7lyjK15WmuNh3p44WYvyS
#
# sudo: false


language: ruby
sudo: false
services:
  - mysql
rvm:
  - 2.3.1
script:
  - bin/rails db:migrate RAILS_ENV=test
  - bundle exec rspec spec
  - bundle exec rake teaspoon USE_COVERAGE=default
gemfile: app/Gemfile
notifications:
  email:
    on_success: never
    on_failure: change
before_install:
  - npm install -g istanbul
  - mysql -e 'CREATE DATABASE IF NOT EXISTS slp_pauselab_test;'
  - "mysql -u root -e \"grant all on slp_pauselab_test.* to 'pauselab';\""
  - cd app
