language: ruby

rvm:
    - 2.3.1

services:
    - mysql

before_script:
    - "mysql -u root -e \"create database slp_pauselab_test;\""
    - "mysql -u root -e \"grant all on slp_pauselab_test.* to 'pauselab';\""
    - cd app

sudo: false

notifications:
    email:
        on_success: never
        on_failure: always
