source 'https://rubygems.org'


gem 'rails', '~> 5.0.0', '>= 5.0.0.1'
gem 'mysql2', '>= 0.3.18', '< 0.5'
gem 'puma', '~> 3.0'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.2'

gem 'jquery-rails'
gem 'turbolinks', '~> 5'
gem 'jbuilder', '~> 2.5'

# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 3.0'
# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'
# testing framework
#gem 'rspec', '~> 3.4.0'

#### gems we are adding ####
gem 'figaro' # easy way to add environment variables
gem 'bootstrap', '~> 4.0.0.alpha5'
source 'https://rails-assets.org' do
  gem 'rails-assets-tether', '>= 1.1.0'
end


# Ruby insists this be added "to avoid polling for changes"
gem 'wdm', '>= 0.1.0' if Gem.win_platform?
gem 'devise' # authentication gem
gem 'cancancan'
# gem 'cancan', github: 'ryanb/cancan', branch: '2.0' # authorization gem
gem 'simple_form' # easier forms
gem 'paperclip','~> 4.2'
gem 'trumbowyg_rails' # Trumbowyg editor
gem 'sanitize' #Sanitize info inside the wysiwig
gem 'font-awesome-sass'
gem 'social-share-button', '~> 0.1.6'
gem 'recaptcha', require: 'recaptcha/rails'
gem 'react-rails'
gem 'rubyzip'

group :development, :test do
  gem 'byebug', platform: :mri # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'capybara'
  gem 'rspec-rails'
  gem 'rails-controller-testing'
  gem 'factory_girl_rails'
  gem 'faker'
  gem 'launchy'
end

group :development do
  # Access an IRB console on exception pages or by using <%= console %> anywhere in the code.
  gem 'web-console'
  gem 'listen', '~> 3.0.5'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
